### PR TITLE
Fix query selector error on PNI product page

### LINKED ISSUE #6199: Query selector not found error on PNI product page
image

Example: https://foundation.mozilla.org/en/privacynotincluded/jabra-elite-85t/

Oddly enough, the error only shows up in Chrome.

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #6199

https://foundation-s-issue-6199-h2ibzx.herokuapp.com/en/privacynotincluded/general-percy-product/

### CODE REVIEW

File: source/js/buyers-guide/analytics-events.js [hunk 1]
```diff
@@ -86,6 +86,8 @@ function getQuerySelectorEvents(pageTitle, productName) {
       category: `buyersguide`,
       action: `submit a product button tap`,
       label: `submit a product button tap on ${pageTitle}`,
+      // Custom properties (not sent to GA)
+      conditionalQuery: `.btn-recommend`,
```
Comment (mmmavis) [inline source/js/buyers-guide/analytics-events.js:90]: `.btn-recommend` button is currently on multiple pages on PNI (just not the product page). This is the least change I could think of to make the console error go away.

Comment (Pomax) [reply source/js/buyers-guide/analytics-events.js:90]: looks good to me! we can re-evaluate if this errors still pops up, or comes back, on pages that are important in the future =)

**Review by Pomax — APPROVED** [review]
