### PR TITLE
Modal close button styling fix

### LINKED ISSUE #4778: Close button visual regression in donation modal
I’ve noticed a minor visual regression in the donation modal, the close button is probably missing a margin.

Screenshot_2020-06-10 Tell Zoom end-to-end encryption for everybody

Tested on Firefox Nightly 79

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #4778

Petition form can't be submitted on review apps so this PR can't be tested there.

To test this PR locally, please make sure the "donation modal" field on the campaign page you are testing has a modal selected.

It's easier to review this PR without whitspace changes: https://github.com/mozilla/foundation.mozilla.org/pull/4839/files?diff=unified&w=1

image

### CODE REVIEW

File: source/js/components/petition/donation-modal.jsx [hunk 1]
```diff
@@ -67,17 +67,15 @@ class DonationModal extends React.Component {
...
-            onClick={(e) => this.props.onClose(e)}
-            tabIndex="0"
-          >
-            <span aria-hidden="true">&times;</span>
-          </button>
-        </div>
+        <button
+          className="close"
+          data-dismiss="modal"
+          aria-label="Close"
```
Comment (TheoChevalier) [inline source/js/components/petition/donation-modal.jsx:73]: Totally unrelated, but this made me realize I had forgotten to make a few of these localizable in the Fluent branch, so thank you :)

Comment (mmmavis) [reply source/js/components/petition/donation-modal.jsx:73]: Thanks for catching this!
