### PR TITLE
9235 - Creep Vote shows chart when zero votes

### LINKED ISSUE #9235: PNI creepy vote results doesn't show selection when it's the first vote
### Describe the bug
If I vote for a creepiness level that hasn't been voted on before then my selection doesn't show up as selected in the results. This isn't a big issue but it does mean that for every new product I spend a lot of time going and voting once for each level so that users don't notice the issue.

### To Reproduce
1. Go to a product that has not been voted on before 
Screen Shot 2022-08-15 at 3 56 45 PM
2. Vote 
Screen Shot 2022-08-15 at 3 56 53 PM
3. See error that it doesn't show you what you voted
Screen Shot 2022-08-15 at 3 56 59 PM

### Expected behavior
What you voted for should be highlighted in the results.
Screen Shot 2022-08-15 at 3 58 10 PM

### PR DESCRIPTION
**Pull request by fessehaye**
Close #9235 

User input now included in Creepiness Chart

Updated factories for easier testing

### CODE REVIEW

File: source/js/buyers-guide/components/creep-vote/creep-vote.jsx [hunk 1]
```diff
@@ -225,20 +246,22 @@ class CreepVote extends Component {
     let userVoteGroup = Math.floor((bins * (this.state.creepiness - 1)) / 100);
     let creepType = CREEPINESS_LABELS[userVoteGroup];
 
+    console.log(this.props.votes.creepiness.vote_breakdown);
```
Comment (danielfmiranda) [inline source/js/buyers-guide/components/creep-vote/creep-vote.jsx:249]:
```suggestion
```

**Review by danielfmiranda — APPROVED** [review]
Hey Simon! This looks good to me and works well when testing, I left one minor suggestion deleting a `console.log` statement, but other than that, approved!
