### PR TITLE
8378 - Fix Directory Listing Filter

### LINKED ISSUE #8378: Public-facing page broken
How to reproduce:

Steps to reproduce: go to https://foundation.mozilla.org/en/what-we-fund/fellowships-and-awards-directory/, click on a year, see that nothing happens. Expected behaviour: clicking on a different year should change the year.

### PR DESCRIPTION
**Pull request by fessehaye**
Closes #8378 

https://foundation-s-8378-fix-v6baotob.herokuapp.com/en/style-guide/#profile_directory

Should be able to click on year labels on the directory-listing component now

### CODE REVIEW

**Comment by Pomax** [comment]
@fessehaye please remember to add a link to the review app's page that shows off the fix =)

File: source/js/foundation/pages/directory-listing-filters.js [hunk 1]
```diff
@@ -48,6 +48,7 @@
 
       // Freeform fields may not contain HTML
       [`name`, `location`, `user_bio`].forEach((type) => {
+        if (!sanitizer) return;
```
Comment (Pomax) [inline source/js/foundation/pages/directory-listing-filters.js:51]: this feels impossible. If `document.createElement` doesn't work, the browser is broken...

**Review by Pomax — CHANGES_REQUESTED** [review]

**Comment by Pomax** [comment]
Hm, something seems to be messing with the title width on load:

**Review by Pomax — DISMISSED** [review]
might need a small CSS tweak to keep the title full width

**Review by Pomax — APPROVED** [review]
\o/
