### PR TITLE
Fix event handler bugs in donation modal

### LINKED ISSUE #6103: Petition modal not working ("X" or "I'll share instead" links)
### Describe the bug
Petition modal not working ("X" or "I'll share instead" links)

### To Reproduce

1. Go to: https://foundation.mozilla.org/en/campaigns/hulu-its-time-ad-disclosure/
2. Add your info to "Sign the Petition"
3. Hit the purple button to add your name
4. Try to click on "X" or "I'll share instead" > BUG: I can't make any of these happen.

### Expected behavior
"X" or "I'll share instead" links should work

### Screenshots
image

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #6103

Petition form cannot be submitted on non-prod environment. Therefore, this will have to be tested locally so we can bring up the donation modal by bypassing the form submission flow.

To test, update `source/js/components/petition/petition.jsx`:

1. in `getInitialState() { ... }`, set `showDonationModal` to `true`
2. go to http://test.example.com:8000/en/campaigns/single-page/ and test
   - the close button (see if it closes the modal)
   - "Yes, I'll chip in" button (it should close the modal as well)
   - "No, I'll share instead) (it should close the modal as well)

### CODE REVIEW

File: source/js/components/petition/donation-modal.jsx [hunk 1]
```diff
@@ -112,6 +128,10 @@ class DonationModal extends Component {
     );
   }
 
+  userElectedCloseModal() {
+    this.props.close();
```
Comment (Pomax) [inline source/js/components/petition/donation-modal.jsx:132]: typo?
```suggestion
    this.props.onClose();
```

**Review by Pomax — CHANGES_REQUESTED** [review]

File: source/js/components/petition/donation-modal.jsx (hunk 1 above)
Comment (mmmavis) [reply source/js/components/petition/donation-modal.jsx:132]: Oops! Yes!

Comment (mmmavis) [reply source/js/components/petition/donation-modal.jsx:132]: Oops! Yes! I created this function last, tested it, and everything worked fine. I was the new script was still building when I tested it out. Thanks for spotting it!

**Review by Pomax — APPROVED** [review]
