### PR TITLE
Fixed copy link bug on iOS

### LINKED ISSUE #2119: Copy link doesn't work on iPhone
Copy link functionality isn't working in Safari on iPhone

### PR DESCRIPTION
**Pull request by mmmavis**
Closes #2119

### CODE REVIEW

File: source/js/buyers-guide/bg-main.js [hunk 1]
```diff
@@ -122,7 +125,20 @@ let main = {
...
+          // For details see https://stackoverflow.com/a/34046084
+          let range = document.createRange();
+          let selection = window.getSelection();
+
+          range.selectNodeContents(textArea);
+
+          selection.removeAllRanges();
+          selection.addRange(range);
+
+          textArea.setSelectionRange(0, 999999); // use a big number to cover anything that could be inside textArea
```
Comment (Pomax) [inline source/js/buyers-guide/bg-main.js]: `textArea.setSelectionRange(0, textArea.value.length);`? We're copying a known string so we don't have to guess some "really high number" here.

File: source/js/buyers-guide/bg-main.js [hunk 2]
```diff
@@ -122,7 +125,20 @@ let main = {
 
           textArea.value = window.location.href;
           document.body.appendChild(textArea);
-          textArea.select();
+
```
Comment (Pomax) [inline source/js/buyers-guide/bg-main.js]: can we remove a newline here?

File: source/js/buyers-guide/bg-main.js (hunk 1 above)
Comment (mmmavis) [reply source/js/buyers-guide/bg-main.js]: love it!
