### PR TITLE
Profile card updates sans location

### LINKED ISSUE #2958: Make location display conditional on profile cards
Profiles include an icon even when location is empty (profile by id  streamfield component). 
 

**To Reproduce**

1. Go to https://foundation.mozilla.org/en/docs/how-do-i-wagtail/profiles-from-pulse/
1. Scroll down and compare Peter and Luca
4. See placemarker by Luca's empty location field. 

**Expected behavior**
When profile has no location, there should be no icon and no extraneous space. 

**Screenshots**

image

### PR DESCRIPTION
**Pull request by youriwims**
Closes #2958 
Related PRs/issues #2990

Test/View fix [here](https://foundation-mofostaging-pr-2997.herokuapp.com/en/profile-cards---no-location-test/).*

*_link updated 22/04/2019_

### CODE REVIEW

**Comment by kristinashu** [comment]
Spacing looks great so I will approve! 

_But_ I noticed a weird bug that is here but also on prod https://github.com/mozilla/foundation.mozilla.org/issues/3000

File: network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js [hunk 1]
```diff
@@ -51,9 +51,20 @@
...
+      let { location } = profile;
+      let metaLocation = "";
+      let cardClass = "person-card";
+
+      if (location) {
+        metaLocation = `<p class="d-flex align-items-center meta-block-location h6-heading my-2">
+              ${profile.location}
+            </p>`;
+      } else {
+        cardClass = "person-card-sans-location";
```
Comment (Pomax) [inline network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js]: Why the rewrite instead of an overide? E.g. `class="person-card"` => `class="person-card no-card-location"`?

File: network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/profile_blocks.html [hunk 2]
```diff
@@ -3,7 +3,7 @@
     {% for profile in profiles %}
       <div class="col-md-6 col-12 mb-5">
 
-        <div class="person-card">
+        <div class="{% if profile.location %} person-card {% else %} person-card-sans-location {% endif %}">
```
Comment (Pomax) [inline network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/profile_blocks.html]: Same as above, why not `class="person-card{% if !profile.location %} no-location{% endif %}"`?

File: source/sass/wagtail/profiles.scss [hunk 3]
```diff
@@ -26,6 +26,19 @@
     grid-template-columns: 0.9fr 2fr;
     min-height: 160px;
   }
+
+  &-sans-location {
```
Comment (Pomax) [inline source/sass/wagtail/profiles.scss]: Let's please not do this, it makes it _really hard_ to find CSS rules. If it's a second class, then using `&.someclass` is fine, but if it's literally only part of the name, then this is going to make it virtually impossible to find anything, because people are going to be searching for the full class as found in the DOM inspector.

Comment (youriwims) [reply source/sass/wagtail/profiles.scss]: I completely understand your point here. 👍

File: network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/profile_blocks.html [hunk 4]
```diff
@@ -1,40 +1,65 @@
...
+            </p>
+            {% endif %}
           </div>
-
-          <div class="bio mt-2 mt-sm-0 pl-sm-2">
-            <p class="m-0">{{ profile.user_bio }}</p>
+          <div class="social-icons">
+            {%if profile.twitter %}
+            <a href="{{ profile.twitter }}" class="twitter small"></a> {% endif
+            %} {%if profile.linkedin %}
```
Comment (gideonthomas) [inline network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/profile_blocks.html]: I don't think you can have the closing `%}` on a separate line. Same with line 54 - you cannot have `{%` and `endif %}` on separate lines

Comment (youriwims) [reply network-api/networkapi/wagtailpages/templates/wagtailpages/blocks/profile_blocks.html]: thanks!

File: network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js [hunk 5]
```diff
@@ -51,9 +51,20 @@
...
+      let { location } = profile;
+      let metaLocation = "";
+      let cardClass = "person-card";
+
+      if (location) {
+        metaLocation = `<p class="d-flex align-items-center meta-block-location h6-heading my-2">
+              ${profile.location}
+            </p>`;
+      } else {
+        cardClass = "person-card no-location";
```
Comment (Pomax) [inline network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js]:
```suggestion
        cardClass = `person-card no-location`;
```

File: network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js [hunk 6]
```diff
@@ -51,9 +51,20 @@
    */
   function loadResults(profiles) {
     let cards = profiles.map(profile => {
+      let { location } = profile;
+      let metaLocation = "";
```
Comment (Pomax) [inline network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js]:
```suggestion
      let metaLocation = ``;
```

File: network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js [hunk 7]
```diff
@@ -51,9 +51,20 @@
...
+      let cardClass = "person-card";
```
Comment (Pomax) [inline network-api/networkapi/wagtailpages/static/js/directory-listing-filters.js]:
```suggestion
      let cardClass = `person-card`;
```
